# Set for ssh support
enable-ssh-support

# Set the cache time out to max.
max-cache-ttl 72000
max-cache-ttl-ssh 72000
default-cache-ttl 72000
default-cache-ttl-ssh 72000

# Keep it from looking for gnome-keyring.
no-allow-external-cache